spring:
  datasource:
    url: jdbc:tc:postgresql:15:///testdb
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    connect-retries: 3

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  level:
    root: WARN
    com.event_driven_order_system: DEBUG
