spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orderdb
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    hikari:
      initialization-fail-timeout: 60000
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    connect-retries: 10
    connect-retries-interval: 5s

  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    listener:
      simple:
        acknowledge-mode: manual
        retry:
          enabled: true
          initial-interval: 1000ms
          max-attempts: 3
          multiplier: 2.0

logging:
  level:
    root: INFO
    com.event_driven_order_system: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

jwt:
  secret: dev-secret-key-apenas-local-nao-usar-em-prod-xpto1234
  expiration: 86400000